version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "importmap"
    directory: "/"
    schedule:
      interval: "weekly"
